from pathlib import Path
import hashlib
root=Path('tach-xep-pdf-v2.3.2')
p=root/'TachXepTrangPDF.cs'
raw=p.read_bytes()
expected_base='ff4279b4dfa8a8972d443ccb200e7e0f1da5602c2a4801dc6696e044fd5caae8'
if hashlib.sha256(raw).hexdigest()!=expected_base: raise SystemExit('unexpected v2.4.4 reconstructed source before v2.4.5 patch')
lines=raw.decode('utf-8-sig').replace('\r\n','\n').splitlines(True)
ops=[
(51,52,['        internal static string StartupLogPath { get { return Path.Combine(LogDirectory, "startup-v2.4.5.log"); } }\n']),
(671,672,['        private const string AppVersion = "2.4.5";\n']),
(688,688,['        private readonly object _previewCacheSync = new object();\n', '        private readonly Dictionary<string, Bitmap> _previewCache = new Dictionary<string, Bitmap>();\n', '        private readonly LinkedList<string> _previewCacheLru = new LinkedList<string>();\n', '        private const int PreviewCacheCapacity = 7;\n', '        private PdfSession _prefetchPdf;\n', '        private CancellationTokenSource _prefetchCts;\n']),
(749,750,['            root.RowStyles.Add(new RowStyle(SizeType.Absolute, 184));\n']),
(761,762,['            header.Height = 52;\n']),
(772,773,['            headerGrid.RowStyles.Add(new RowStyle(SizeType.Absolute, 30));\n']),
(798,799,['            toolbar.Height = 132;\n']),
(800,801,['            toolbar.Padding = new Padding(12, 3, 12, 3);\n']),
(807,809,['            toolbarGrid.RowStyles.Add(new RowStyle(SizeType.Absolute, 25));\n', '            toolbarGrid.RowStyles.Add(new RowStyle(SizeType.Absolute, 44));\n']),
(870,872,['            TableLayoutPanel manualGrid = new TableLayoutPanel(); manualGrid.Dock = DockStyle.Fill; manualGrid.ColumnCount = 1; manualGrid.RowCount = 2; manualGrid.RowStyles.Add(new RowStyle(SizeType.Percent, 100)); manualGrid.RowStyles.Add(new RowStyle(SizeType.Absolute, 0)); manual.Controls.Add(manualGrid);\n', '            FlowLayoutPanel manualButtons = new FlowLayoutPanel(); manualButtons.Dock = DockStyle.Fill; manualButtons.WrapContents = true; manualButtons.AutoScroll = false; manualGrid.Controls.Add(manualButtons, 0, 0);\n']),
(902,902,['                // v2.4.5: keep the maximized chrome compact so the PDF gets more vertical space,\n', '                // but reserve a taller toolbar on normal/narrow windows so no command is clipped.\n', '                bool compactChrome = ClientSize.Width >= 1380;\n', '                float topHeight = compactChrome ? 184f : 218f;\n', '                root.RowStyles[0].Height = topHeight;\n', '                header.Height = 52;\n', '                toolbar.Height = compactChrome ? 132 : 166;\n', '                manualButtons.WrapContents = !compactChrome;\n']),
(1086,1086,['                _prefetchPdf = new PdfSession(_workPath);\n']),
(1333,1334,['        private string PreviewCacheKey(object model)\n']),
(1335,1339,['            SourceFace sf = model as SourceFace;\n', '            if (sf != null)\n', '                return "S:" + sf.Id.ToString("N") + ":" + sf.OriginalSourceIndex.ToString() + ":r" + sf.Rotation.ToString();\n', '            OutputPage op = model as OutputPage;\n', '            if (op != null)\n', '                return "O:" + op.Id.ToString("N") + ":" + op.OriginalSourceIndex.ToString() + ":sr" + op.SourceRotation.ToString() + ":h" + op.Half.ToString() + ":c" + ((int)Math.Round(op.CutPercent * 10.0)).ToString() + ":er" + op.ExtraRotation.ToString();\n', '            return "";\n', '        }\n', '\n', '        private Bitmap RenderPreviewBitmap(PdfSession pdf, object model, int maxDimension)\n', '        {\n', '            if (pdf == null || model == null) return null;\n', '            if (model is SourceFace)\n']),
(1340,1341,['                SourceFace sf = (SourceFace)model;\n', '                using (Bitmap raw = pdf.RenderPageMax(sf.OriginalSourceIndex, maxDimension))\n', '                    return ImageOps.Rotate(raw, sf.Rotation);\n', '            }\n', '            OutputPage op = model as OutputPage;\n', '            if (op == null) return null;\n', '            using (Bitmap raw = pdf.RenderPageMax(op.OriginalSourceIndex, maxDimension))\n', '            using (Bitmap spread = ImageOps.Rotate(raw, op.SourceRotation))\n', '            using (Bitmap half = ImageOps.CropHalf(spread, op.Half, op.CutPercent))\n', '                return ImageOps.Rotate(half, op.ExtraRotation);\n', '        }\n', '\n', '        private bool TryGetCachedPreview(string key, out Bitmap copy)\n', '        {\n', '            copy = null;\n', '            if (string.IsNullOrEmpty(key)) return false;\n', '            lock (_previewCacheSync)\n', '            {\n', '                Bitmap cached;\n', '                if (!_previewCache.TryGetValue(key, out cached) || cached == null) return false;\n', '                LinkedListNode<string> node = _previewCacheLru.Find(key);\n', '                if (node != null) { _previewCacheLru.Remove(node); _previewCacheLru.AddFirst(node); }\n', '                copy = new Bitmap(cached);\n', '                return true;\n', '            }\n', '        }\n', '\n', '        private void PutPreviewCache(string key, Bitmap image)\n', '        {\n', '            if (string.IsNullOrEmpty(key) || image == null) return;\n', '            lock (_previewCacheSync)\n', '            {\n', '                Bitmap old;\n', '                if (_previewCache.TryGetValue(key, out old))\n']),
(1342,1345,['                    _previewCache[key] = new Bitmap(image);\n', '                    if (old != null) old.Dispose();\n', '                    LinkedListNode<string> existing = _previewCacheLru.Find(key);\n', '                    if (existing != null) _previewCacheLru.Remove(existing);\n', '                }\n', '                else _previewCache[key] = new Bitmap(image);\n', '                _previewCacheLru.AddFirst(key);\n', '                while (_previewCacheLru.Count > PreviewCacheCapacity)\n', '                {\n', '                    string victim = _previewCacheLru.Last.Value;\n', '                    _previewCacheLru.RemoveLast();\n', '                    Bitmap victimImage;\n', '                    if (_previewCache.TryGetValue(victim, out victimImage))\n', '                    {\n', '                        _previewCache.Remove(victim);\n', '                        if (victimImage != null) victimImage.Dispose();\n', '                    }\n']),
(1347,1348,['        }\n', '\n', '        private void ClearPreviewCache()\n', '        {\n', '            lock (_previewCacheSync)\n', '            {\n', '                foreach (Bitmap b in _previewCache.Values) if (b != null) try { b.Dispose(); } catch { }\n', '                _previewCache.Clear();\n', '                _previewCacheLru.Clear();\n', '            }\n', '        }\n', '\n', '        private void SchedulePreviewPrefetch(int centerIndex)\n', '        {\n', '            PdfSession pdf = _prefetchPdf;\n', '            if (pdf == null || _list == null || centerIndex < 0) return;\n', '            List<object> nearby = new List<object>();\n', '            int[] offsets = new int[] { 1, -1, 2, -2 };\n', '            for (int i = 0; i < offsets.Length; i++)\n', '            {\n', '                int idx = centerIndex + offsets[i];\n', '                if (idx >= 0 && idx < _list.Items.Count) nearby.Add(_list.Items[idx].Tag);\n', '            }\n', '            if (nearby.Count == 0) return;\n', '            CancellationTokenSource next = new CancellationTokenSource();\n', '            CancellationTokenSource old = Interlocked.Exchange(ref _prefetchCts, next);\n', '            if (old != null) { try { old.Cancel(); } catch { } old.Dispose(); }\n', '            CancellationToken token = next.Token;\n', '            Task.Run(delegate\n', '            {\n', '                for (int i = 0; i < nearby.Count; i++)\n', '                {\n', '                    if (token.IsCancellationRequested || pdf != _prefetchPdf) break;\n', '                    object model = nearby[i];\n', '                    string key = PreviewCacheKey(model);\n', '                    Bitmap cached;\n', '                    if (TryGetCachedPreview(key, out cached)) { cached.Dispose(); continue; }\n', '                    Bitmap rendered = null;\n', '                    try\n', '                    {\n', '                        rendered = RenderPreviewBitmap(pdf, model, 1500);\n', '                        if (rendered != null && !token.IsCancellationRequested && pdf == _prefetchPdf) PutPreviewCache(key, rendered);\n', '                    }\n', '                    catch (Exception ex) { AppDiagnostics.LogException("PREVIEW_PREFETCH_FAIL", ex); }\n', '                    finally { if (rendered != null) rendered.Dispose(); }\n', '                }\n', '            }, token);\n']),
(1358,1358,['            string cacheKey = PreviewCacheKey(model);\n']),
(1359,1360,['            // v2.4.5: one visual transition only. Never stretch the 104x78 thumbnail into Preview.\n', '            // Cancel any render for the previously selected page before consulting the real-page cache.\n', '            CancellationTokenSource previousCts = Interlocked.Exchange(ref _previewCts, null);\n', '            if (previousCts != null) { try { previousCts.Cancel(); } catch { } previousCts.Dispose(); }\n', '            // If the real page is already cached, switch immediately. Otherwise keep the current\n', '            // page on screen until the requested real-aspect preview is ready, then atomically swap once.\n', '            Bitmap cachedPreview;\n', '            if (TryGetCachedPreview(cacheKey, out cachedPreview))\n', '            {\n', '                _previewModelKey = wantedKey;\n', '                SetPreview(cachedPreview);\n', '                SchedulePreviewPrefetch(idx);\n', '                return;\n', '            }\n']),
(1362,1364,['            _previewCts = nextCts;\n']),
(1368,1371,[]),
(1377,1388,['                    return RenderPreviewBitmap(pdf, model, 1500);\n']),
(1392,1393,['                if (rendered == null || token.IsCancellationRequested || ticket != _previewTicket || pdf != (_previewPdf ?? _pdf) || wantedKey != currentKey)\n']),
(1394,1395,['                    if (rendered != null) rendered.Dispose();\n']),
(1397,1397,['                PutPreviewCache(cacheKey, rendered);\n']),
(1399,1399,['                SchedulePreviewPrefetch(idx);\n']),
(1986,1986,['                Bitmap beforeRapid = _previewMaster;\n']),
(1988,1988,['                if (_thumbs.ImageSize.Width == _previewMaster.Width && _thumbs.ImageSize.Height == _previewMaster.Height) throw new InvalidOperationException("Workflow smoke: tiny thumbnail leaked into Preview.");\n']),
(2031,2031,['            try { if (_prefetchCts != null) _prefetchCts.Cancel(); } catch { }\n']),
(2032,2032,['            if (_prefetchCts != null) { _prefetchCts.Dispose(); _prefetchCts = null; }\n']),
(2034,2035,['            ClearPreviewCache();\n', '            _preview.Image = null; _pdf = null; _previewPdf = null; _prefetchPdf = null;\n']),
(2072,2073,['            if (!fr.Contains(cr)) throw new InvalidOperationException("UI control clipped/outside form: " + text + " bounds=" + cr.ToString());\n']),
(2133,2134,['                            if (previewTitle == null) throw new InvalidOperationException("Preview toolbar missing.");\n', '                            Rectangle previewRc = previewTitle.RectangleToScreen(previewTitle.ClientRectangle);\n', '                            Rectangle formRcTop = form.RectangleToScreen(form.ClientRectangle);\n', '                            Control lastTopControl = FindControlByText(form, "Xóa trang PDF");\n', '                            if (lastTopControl != null && previewRc.Top < lastTopControl.RectangleToScreen(lastTopControl.ClientRectangle).Bottom - 2) throw new InvalidOperationException("Preview toolbar overlaps top commands.");\n', '                            int maxExpectedTop = form.ClientSize.Width >= 1380 ? 205 : 242;\n', '                            if (previewRc.Top > formRcTop.Top + maxExpectedTop) throw new InvalidOperationException("Top chrome wastes too much vertical space: " + previewRc.Top.ToString());\n']),
]
for i1,i2,repl in reversed(ops): lines[i1:i2]=repl
out=''.join(lines).encode('utf-8-sig')
expected_final='7051ace6f2d9de56553e268d2e8bf6a88bcdc67a15a8610e2c04f215f83398d6'
actual=hashlib.sha256(out).hexdigest()
if actual!=expected_final: raise SystemExit('v2.4.5 source patch checksum mismatch actual='+actual)
p.write_bytes(out)
launcher=root/'launcher.cpp'
ls=launcher.read_text(encoding='utf-8-sig')
ls2=ls.replace('2.4.4','2.4.5')
if ls2==ls: raise SystemExit('launcher v2.4.4 marker missing')
launcher.write_text(ls2,encoding='utf-8-sig')
print('PATCH_V245_PAGE_CACHE_COMPACT_UI_OK source_sha256='+actual)
