from pathlib import Path
p = Path('tach-xep-pdf-v2.3.2/TachXepTrangPDF.cs')
s = p.read_text(encoding='utf-8-sig')

# Preview toolbar: percent zoom + Fit to window; aspect-safe PictureBox.
old = '''            Panel previewTop = new Panel(); previewTop.Dock = DockStyle.Fill; centerLayout.Controls.Add(previewTop, 0, 0);\n            Label pv = new Label(); pv.Text = "XEM TRƯỚC"; pv.Font = new Font("Segoe UI", 11f, FontStyle.Bold); pv.Location = new Point(2, 8); pv.AutoSize = true; previewTop.Controls.Add(pv);\n            Label zl = new Label(); zl.Text = "Thu phóng:"; zl.Location = new Point(120, 9); zl.AutoSize = true; previewTop.Controls.Add(zl);\n            _zoom = new TrackBar(); _zoom.Minimum = 50; _zoom.Maximum = 250; _zoom.TickFrequency = 25; _zoom.Value = 100; _zoom.Location = new Point(190, 0); _zoom.Width = 300; _zoom.ValueChanged += delegate { ApplyZoom(); }; previewTop.Controls.Add(_zoom);\n            _previewScroll = new Panel(); _previewScroll.Dock = DockStyle.Fill; _previewScroll.AutoScroll = true; _previewScroll.BackColor = Color.FromArgb(45, 48, 52); centerLayout.Controls.Add(_previewScroll, 0, 1);\n            _preview = new PictureBox(); _preview.BackColor = Color.White; _preview.SizeMode = PictureBoxSizeMode.StretchImage; _preview.Location = new Point(20, 20); _previewScroll.Controls.Add(_preview);'''
new = '''            TableLayoutPanel previewTop = new TableLayoutPanel(); previewTop.Dock = DockStyle.Fill; previewTop.ColumnCount = 6; previewTop.RowCount = 1;\n            previewTop.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 110)); previewTop.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 115));\n            previewTop.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 85)); previewTop.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 78));\n            previewTop.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 30)); previewTop.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100));\n            centerLayout.Controls.Add(previewTop, 0, 0);\n            Label pv = new Label(); pv.Text = "XEM TRƯỚC"; pv.Font = new Font("Segoe UI", 11f, FontStyle.Bold); pv.Dock = DockStyle.Fill; pv.TextAlign = ContentAlignment.MiddleLeft; previewTop.Controls.Add(pv, 0, 0);\n            Button fit = MakeButton("Vừa cửa sổ", 104, false); fit.Height = 30; fit.Margin = new Padding(2, 4, 6, 0); fit.Click += delegate { if (_zoom.Value != 100) _zoom.Value = 100; else ApplyZoom(); }; previewTop.Controls.Add(fit, 1, 0);\n            Label zl = new Label(); zl.Text = "Thu phóng:"; zl.Dock = DockStyle.Fill; zl.TextAlign = ContentAlignment.MiddleRight; previewTop.Controls.Add(zl, 2, 0);\n            _zoom = new NumericUpDown(); _zoom.Minimum = 50; _zoom.Maximum = 300; _zoom.Increment = 25; _zoom.Value = 100; _zoom.TextAlign = HorizontalAlignment.Center; _zoom.Width = 70; _zoom.Margin = new Padding(4, 7, 2, 0); _zoom.ValueChanged += delegate { ApplyZoom(); }; previewTop.Controls.Add(_zoom, 3, 0);\n            Label zoomPct = new Label(); zoomPct.Text = "%"; zoomPct.Dock = DockStyle.Fill; zoomPct.TextAlign = ContentAlignment.MiddleLeft; previewTop.Controls.Add(zoomPct, 4, 0);\n            Label zoomHint = new Label(); zoomHint.Text = "100% = vừa cửa sổ"; zoomHint.ForeColor = Color.DimGray; zoomHint.Dock = DockStyle.Fill; zoomHint.TextAlign = ContentAlignment.MiddleLeft; previewTop.Controls.Add(zoomHint, 5, 0);\n            _previewScroll = new Panel(); _previewScroll.Dock = DockStyle.Fill; _previewScroll.AutoScroll = true; _previewScroll.BackColor = Color.FromArgb(45, 48, 52); centerLayout.Controls.Add(_previewScroll, 0, 1); _previewScroll.Resize += delegate { ApplyZoom(); };\n            _preview = new PictureBox(); _preview.BackColor = Color.White; _preview.SizeMode = PictureBoxSizeMode.Zoom; _preview.Location = new Point(16, 16); _previewScroll.Controls.Add(_preview);'''
if old not in s: raise SystemExit('preview top block not found')
s = s.replace(old, new, 1)

s = s.replace('Label ih = new Label(); ih.Text = "THÔNG TIN & HƯỚNG DẪN"; ih.Font = new Font("Segoe UI", 11f, FontStyle.Bold);', 'Label ih = new Label(); ih.Text = "HƯỚNG DẪN"; ih.Font = new Font("Segoe UI", 10f, FontStyle.Bold);', 1)
s = s.replace('help.Font = new Font("Segoe UI", 9.5f);', 'help.Font = new Font("Segoe UI", 8.8f);', 1)

old = '''        private void ApplyZoom()\n        {\n            if (_previewScroll == null || _preview == null || _zoom == null) return;\n            if (_previewMaster == null || _previewScroll.ClientSize.Width <= 20 || _previewScroll.ClientSize.Height <= 20) { _preview.Size = new Size(10, 10); return; }\n            double fit = Math.Min((_previewScroll.ClientSize.Width - 40) / (double)_previewMaster.Width, (_previewScroll.ClientSize.Height - 40) / (double)_previewMaster.Height);\n            fit = Math.Max(0.02, fit);\n            double scale = fit * _zoom.Value / 100.0;\n            _preview.Size = new Size(Math.Max(1, (int)Math.Round(_previewMaster.Width * scale)), Math.Max(1, (int)Math.Round(_previewMaster.Height * scale)));\n            _preview.Location = new Point(20, 20);\n        }'''
new = '''        private void ApplyZoom()\n        {\n            if (_previewScroll == null || _preview == null || _zoom == null) return;\n            if (_previewMaster == null || _previewScroll.ClientSize.Width <= 20 || _previewScroll.ClientSize.Height <= 20) { _preview.Size = new Size(10, 10); return; }\n            int margin = 16;\n            int aw = Math.Max(1, _previewScroll.ClientSize.Width - margin * 2); int ah = Math.Max(1, _previewScroll.ClientSize.Height - margin * 2);\n            double fitScale = Math.Min(aw / (double)_previewMaster.Width, ah / (double)_previewMaster.Height); fitScale = Math.Max(0.02, fitScale);\n            double scale = fitScale * (double)_zoom.Value / 100.0;\n            int w = Math.Max(1, (int)Math.Round(_previewMaster.Width * scale)); int h = Math.Max(1, (int)Math.Round(_previewMaster.Height * scale));\n            int x = w < aw ? margin + (aw - w) / 2 : margin; int y = h < ah ? margin + (ah - h) / 2 : margin;\n            _preview.SizeMode = PictureBoxSizeMode.Zoom; _preview.Size = new Size(w, h); _preview.Location = new Point(x, y);\n        }'''
if old not in s: raise SystemExit('ApplyZoom block not found')
s = s.replace(old, new, 1)

p.write_text(s, encoding='utf-8-sig')
print('PATCH_V235B_PREVIEW_OK')
