from pathlib import Path
p = Path('tach-xep-pdf-v2.3.2/TachXepTrangPDF.cs')
s = p.read_text(encoding='utf-8-sig')

# Plain arrows navigate selection and refresh preview; Ctrl+arrows preserve reorder.
old = '''        private void ListKeyDown(object sender, KeyEventArgs e)\n        {\n            if (e.KeyCode == Keys.Up) { e.SuppressKeyPress = true; MoveSelectedBy(-1); }\n            else if (e.KeyCode == Keys.Down) { e.SuppressKeyPress = true; MoveSelectedBy(1); }\n            else if (e.KeyCode == Keys.Delete) { e.SuppressKeyPress = true; DeleteSelected(); }\n            else if (e.Control && e.KeyCode == Keys.Z) { e.SuppressKeyPress = true; Undo(); }\n            else if (e.Control && e.KeyCode == Keys.Y) { e.SuppressKeyPress = true; Redo(); }\n        }\n\n        private void MoveSelectedBy(int delta)'''
new = '''        private void ListKeyDown(object sender, KeyEventArgs e)\n        {\n            if (e.Control && e.KeyCode == Keys.Up) { e.SuppressKeyPress = true; MoveSelectedBy(-1); }\n            else if (e.Control && e.KeyCode == Keys.Down) { e.SuppressKeyPress = true; MoveSelectedBy(1); }\n            else if (e.KeyCode == Keys.Up) { e.SuppressKeyPress = true; SelectAdjacent(-1); }\n            else if (e.KeyCode == Keys.Down) { e.SuppressKeyPress = true; SelectAdjacent(1); }\n            else if (e.KeyCode == Keys.Delete) { e.SuppressKeyPress = true; DeleteSelected(); }\n            else if (e.Control && e.KeyCode == Keys.Z) { e.SuppressKeyPress = true; Undo(); }\n            else if (e.Control && e.KeyCode == Keys.Y) { e.SuppressKeyPress = true; Redo(); }\n        }\n\n        private void SelectAdjacent(int delta)\n        {\n            if (_busy || _list == null || _list.Items.Count == 0) return;\n            int idx = SelectedIndex < 0 ? 0 : SelectedIndex; int target = Math.Max(0, Math.Min(_list.Items.Count - 1, idx + delta));\n            _suspendSelection = true;\n            try { for (int i = 0; i < _list.Items.Count; i++) _list.Items[i].Selected = false; _list.Items[target].Selected = true; _list.Items[target].Focused = true; _list.EnsureVisible(target); }\n            finally { _suspendSelection = false; }\n            UpdateSelectionLabel(); UpdateCutControl(); LoadSelectedPreviewAsync(); ActiveControl = _list; _list.Focus();\n        }\n\n        private void MoveSelectedBy(int delta)'''
if old not in s: raise SystemExit('keyboard block not found')
s = s.replace(old, new, 1)
old = '''        protected override bool ProcessCmdKey(ref Message msg, Keys keyData)\n        {\n            // Keep page ordering keyboard control continuous after a toolbar click.\n            // Numeric/zoom controls retain their own arrow-key behavior.\n            if (!_busy && _pdf != null && SelectedIndex >= 0 && !_cut.ContainsFocus && !_zoom.ContainsFocus)\n            {\n                if (keyData == Keys.Up && (_list.ContainsFocus || ActiveControl is Button))\n                {\n                    MoveSelectedBy(-1);\n                    return true;\n                }\n                if (keyData == Keys.Down && (_list.ContainsFocus || ActiveControl is Button))\n                {\n                    MoveSelectedBy(1);\n                    return true;\n                }\n            }\n            return base.ProcessCmdKey(ref msg, keyData);\n        }'''
new = '''        protected override bool ProcessCmdKey(ref Message msg, Keys keyData)\n        {\n            if (!_busy && _pdf != null && SelectedIndex >= 0 && !_cut.ContainsFocus && !_zoom.ContainsFocus)\n            {\n                bool pageContext = _list.ContainsFocus || ActiveControl is Button;\n                if (pageContext && keyData == (Keys.Control | Keys.Up)) { MoveSelectedBy(-1); return true; }\n                if (pageContext && keyData == (Keys.Control | Keys.Down)) { MoveSelectedBy(1); return true; }\n                if (pageContext && keyData == Keys.Up) { SelectAdjacent(-1); return true; }\n                if (pageContext && keyData == Keys.Down) { SelectAdjacent(1); return true; }\n            }\n            return base.ProcessCmdKey(ref msg, keyData);\n        }'''
if old not in s: raise SystemExit('ProcessCmdKey block not found')
s = s.replace(old, new, 1)

# UI smoke requires restored zoom controls and narrow guide column.
s = s.replace('''                            "XEM TRƯỚC",\n                            "THÔNG TIN & HƯỚNG DẪN"''', '''                            "XEM TRƯỚC",\n                            "Vừa cửa sổ",\n                            "HƯỚNG DẪN"''', 1)
s = s.replace('''                            foreach (string text in required) AssertUiControlVisible(form, text);\n                        }''', '''                            foreach (string text in required) AssertUiControlVisible(form, text);\n                            Control guide = FindControlByText(form, "HƯỚNG DẪN");\n                            if (guide != null && guide.Width > form.ClientSize.Width * 0.17) throw new InvalidOperationException("Right info pane too wide: " + guide.Width.ToString());\n                        }''', 1)

p.write_text(s, encoding='utf-8-sig')
print('PATCH_V235D_NAV_SMOKE_OK')
